server:
  port: 10010
spring:
  application:
    name: study-zuul
zuul:
  routes:
    service-provider: /service-provider/**  # 转发到的服务名：被替换的url
    service-consumer: /consumer/**
  prefix: /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

