server:
  port: 10086
spring:
  application:
    name: study-eureka # 应用名称，会在Eureka中显示
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
  server:
    eviction-interval-timer-in-ms: 10000 # 对失效的服务剔除的时间间隔
    enable-self-preservation: false # 关闭自我保护模式（默认为开启）
